### ISSUE TITLE
Error: object 'jnk_subnetwork' not found

### ISSUE THREAD

**Issue by sofija-marinkovic** [XinmengLiao/Open_MoA#1]
Hi, I was going through the algorithm scripts of Open MoA, and I noticed some potential errors in the Shortest_Path.R script.
jnk_subnetwork is neither defined nor provided, and it seemed to me that lines 24 and 25 of the code will not work:
```
ver.A <- jnk_subnetwork[,1]
ver.B <- jnk_subnetwork[,2]
```
I ran the Weights_Calculation.R script to obtain the TGFb1_specific_weighted_subnetwork.csv file, and then I ran the Shortest_Path.R script, and it failed with an **Error: object 'jnk_subnetwork' not found**.
Another thing I noticed is that the code contains ver.A1 and ver.B1 that are not defined. Should A1 and B1 be renamed to A and B?
I really appreciate your help with this!

**Comment by XinmengLiao** [comment]
> Hi, I was going through the algorithm scripts of Open MoA, and I noticed some potential errors in the Shortest_Path.R script. jnk_subnetwork is neither defined nor provided, and it seemed to me that lines 24 and 25 of the code will not work:
> 
> ```
> ver.A <- jnk_subnetwork[,1]
> ver.B <- jnk_subnetwork[,2]
> ```
> 
> I ran the Weights_Calculation.R script to obtain the TGFb1_specific_weighted_subnetwork.csv file, and then I ran the Shortest_Path.R script, and it failed with an **Error: object 'jnk_subnetwork' not found**. Another thing I noticed is that the code contains ver.A1 and ver.B1 that are not defined. Should A1 and B1 be renamed to A and B? I really appreciate your help with this!

Hi Sofija, 
We apologise for the errors in our original codes. We already debugged and uploaded the latest version of codes for Open MoA functions (https://github.com/XinmengLiao/Open_MoA/tree/main/Algorithms). A brief tutorial (Tutorial.R) is also uploaded in the same directory for better understanding and utilisation of Open MoA.

**Comment by sofija-marinkovic** [comment]
Thank you, now everything works fine! I will close the issue.
